const rp = require("request-promise");
const TOKEN =
  "Beaer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2ODc5Mjk1OTgsInVzZXJJZCI6ImViZTU3NTFhLWEwNWItNDZiNi05MWI0LTFjMTEyYTkwZjYzOCIsImVtYWlsIjoic3V5YXNoLmt1bWFyQGZyZXRyb24uY29tIiwibW9iaWxlTnVtYmVyIjoiOTU1NTEwNzcwMCIsIm9yZ0lkIjoiNDk1Yjg3MjgtYzc2MS00ZmE3LTgzZmUtZGI3NWE3ZDYzMjIxIiwibmFtZSI6IlN1eWFzaCAiLCJvcmdUeXBlIjoiRkxFRVRfT1dORVIiLCJpc0dvZCI6dHJ1ZSwicG9ydGFsVHlwZSI6ImJhc2ljIn0.cUwGP7pBSmG2x3Ke82UG_kfovN0lIyD-aSNXcIKgar8";
const $event = {
  creationTime: 1687845712423,
  customFields: [
    {
      indexedValue: ["EDD_1688796105030"],
      fieldKey: "EDD",
      multiple: false,
      description: "",
      remark: "",
      uuid: null,
      required: false,
      accessType: null,
      input: "string",
      unit: "",
      valueType: "string",
      options: [],
      fieldType: "text",
      value: "1688796105030",
      isRemark: false,
    },
    {
      indexedValue: ["Pickup Date_6/27/2023, 11:31:52 AM"],
      fieldKey: "Pickup Date",
      multiple: false,
      description: "",
      remark: "",
      uuid: null,
      required: false,
      accessType: null,
      input: "string",
      unit: "",
      valueType: "string",
      options: [],
      fieldType: "text",
      value: "6/27/2023, 11:31:52 AM",
      isRemark: false,
    },
    {
      indexedValue: ["Shipment Date_6/27/2023, 11:31:33 AM"],
      fieldKey: "Shipment Date",
      multiple: false,
      description: "",
      remark: "",
      uuid: null,
      required: false,
      accessType: null,
      input: "string",
      unit: "",
      valueType: "string",
      options: [],
      fieldType: "text",
      value: "6/27/2023, 11:31:33 AM",
      isRemark: false,
    },
    {
      indexedValue: ["Device Submitted_NO"],
      fieldKey: "Device Submitted",
      multiple: false,
      description: "Device Submitted?",
      remark: "",
      uuid: "f23b53b4-6431-4239-80af-6a16a6a5629f",
      required: false,
      accessType: null,
      input: "",
      unit: "",
      valueType: "string",
      options: ["Yes", "No"],
      fieldType: "yes-no",
      value: "NO",
      isRemark: false,
    },
    {
      indexedValue: ["Device Submit Date_null"],
      fieldKey: "Device Submit Date",
      multiple: true,
      description: "Device Submit Date",
      remark: "",
      uuid: "378509c4-97f3-4c3f-a312-4f03ece7e1d5",
      required: false,
      accessType: null,
      input: "date",
      unit: "",
      valueType: "string",
      options: [],
      fieldType: "dateTime",
      value: null,
      isRemark: false,
    },
    {
      indexedValue: ["Trip Type_Round Trip"],
      fieldKey: "Trip Type",
      multiple: false,
      description: null,
      remark: null,
      uuid: null,
      required: false,
      accessType: null,
      input: "string",
      unit: null,
      valueType: "string",
      options: null,
      fieldType: "text",
      value: "Round Trip",
      isRemark: false,
    },
    {
      indexedValue: ["Vehicle Type_Canter"],
      fieldKey: "Vehicle Type",
      multiple: false,
      description: null,
      remark: null,
      uuid: null,
      required: false,
      accessType: null,
      input: "string",
      unit: null,
      valueType: "string",
      options: null,
      fieldType: "text",
      value: "Canter",
      isRemark: false,
    },
    {
      indexedValue: ["Vendor Name_Vikas sharma transport"],
      fieldKey: "Vendor Name",
      multiple: false,
      description: null,
      remark: null,
      uuid: null,
      required: false,
      accessType: null,
      input: "string",
      unit: null,
      valueType: "string",
      options: null,
      fieldType: "text",
      value: "Vikas sharma transport",
      isRemark: false,
    },
    {
      indexedValue: ["Mode_Dedicated"],
      fieldKey: "Mode",
      multiple: false,
      description: null,
      remark: null,
      uuid: null,
      required: false,
      accessType: null,
      input: "string",
      unit: null,
      valueType: "string",
      options: null,
      fieldType: "text",
      value: "Dedicated",
      isRemark: false,
    },
    {
      indexedValue: ["Stock Type_F&V Morning,LT Group 2"],
      fieldKey: "Stock Type",
      multiple: false,
      description: null,
      remark: null,
      uuid: null,
      required: false,
      accessType: null,
      input: "string",
      unit: null,
      valueType: "string",
      options: null,
      fieldType: "text",
      value: "F&V Morning,LT Group 2",
      isRemark: false,
    },
    {
      indexedValue: ["Is Executed_Yes"],
      fieldKey: "Is Executed",
      multiple: false,
      description: null,
      remark: null,
      uuid: null,
      required: false,
      accessType: null,
      input: null,
      unit: null,
      valueType: "string",
      options: ["Yes", "No"],
      fieldType: "yes-no",
      value: "Yes",
      isRemark: false,
    },
  ],
  transportationMode: "ByRoad",
  freightUnitLineItemId: null,
  lastSyncUpTime: 1687846873828,
  updates: {
    traceID: "shservicescheduletask_3_2942",
    resourceId: "7606c6a5-25c7-4b98-84b4-4e8cfd27ba86",
    updatedBy: "SYSTEM",
    changes: null,
    sourceOfInformation: null,
    description: null,
    forwardReasons: ["HEART-BEAT"],
    userId: null,
    uuid: "abaf64aa-346d-4db0-ab5b-7c0a497268ea",
    revision: 72,
    time: 1687935431543,
    forwardedFrom: null,
    resourceType: "ShipmentObject",
    updateType: null,
  },
  isActive: true,
  uuid: "7606c6a5-25c7-4b98-84b4-4e8cfd27ba86",
  issues: null,
  branch: {
    address: ",Kolkata,West Bengal,India,in",
    updatedBy: null,
    customFields: null,
    regionName: null,
    externalId: null,
    branchName: null,
    type: ["IT", "Operation", "Sales", ""],
    updates: null,
    orgId: "495b8728-c761-4fa7-83fe-db75a7d63221",
    areaId: null,
    geoLocation: null,
    regionId: null,
    areaName: null,
    name: "BLINKIT ",
    zoneId: null,
    _id: "73dd03c8-0798-4f99-bf75-930d58481ac0",
    zoneName: null,
    contacts: [],
    officeType: null,
    materialServices: null,
  },
  orgId: "495b8728-c761-4fa7-83fe-db75a7d63221",
  shipmentType: "DirectLeg",
  completionTime: null,
  routeId: null,
  shipmentTrackingStatus: "At Delivery Point",
  lastForwardTime: 1687935431555,
  runningStatus: null,
  delayTrackingStatus: "UP TO DATE",
  delayReasonLastUpdateTime: null,
  links: null,
  shipmentDate: 1687845758000,
  delayReason: null,
  shipmentNumber: "2391441",
  originalEdd: 1688796105030,
  edd: 1688796105030,
  delayReasonUpdateExpiryTime: null,
  externalShipmentId: null,
  fleetInfo: {
    isTrackingEnable: null,
    forwardingAgent: {
      geoFence: null,
      documents: null,
      customFields: null,
      isPortalEnabled: false,
      type: "vendor",
      updates: null,
      uuid: "928a78b7-6063-4b2f-81fe-2dd315540247",
      orgId: null,
      firmType: null,
      gstn: "123456789009876",
      voterId: null,
      verificationTicketId: null,
      group: {
        name: "lorryOwner",
        partnerType: null,
        uuid: null,
        orgId: null,
      },
      address:
        '{"address":",rajan store,Undefined Minor Road,Karunagappally,Kollam,Kerala,690574,India,in","city":null,"state":null,"pincode":null}',
      verificationStatus: null,
      externalId: null,
      panNumber: "CCBPJ7538R",
      aadharNo: null,
      parentId: null,
      places: null,
      route: null,
      name: "karan mishra ",
      location: null,
      fretronId: null,
      contacts: [
        {
          emails: [""],
          address: null,
          mobileNumbers: [],
          mobileNumber: null,
          name: "karan mishra ",
          type: null,
        },
      ],
      status: "ACTIVE",
    },
    verificationStatus: null,
    trackingMode: "MANUAL",
    broker: null,
    uuid: null,
    orgId: null,
    vehicle: {
      vtsDeviceId: null,
      kmDriven: null,
      secondaryDriverId: null,
      attachedDocs: [],
      customFields: [],
      floorType: null,
      description: null,
      source: "FRETRON",
      isTrackingEnabled: false,
      updates: null,
      uuid: null,
      branch: null,
      orgId: null,
      vehicleLoadType: null,
      associatedWith: null,
      isDeleted: null,
      customerId: null,
      vehicleModel: null,
      mileageEmpty: null,
      mileageLoaded: null,
      vehicleType: null,
      groups: null,
      externalId: null,
      updateTime: null,
      sharedWith: [],
      baseLocationId: null,
      vehicleMake: null,
      vehicleRegistrationNumber: "HR39E7292",
      chassisNumber: null,
      driverId: null,
      createTime: null,
      loadCapacity: null,
      truckLength: null,
      category: null,
      groupsExtended: null,
    },
    driver: null,
    fleetType: "Owned",
    fleetOwner: null,
    trainInfo: null,
    lbsNumber: null,
    secondaryDriver: null,
    device: null,
    status: null,
  },
  syncUpDueTime: 1782454873833,
  billingStatus: null,
  currentLocation: null,
  alerts: [],
  equipments: null,
  tripType: "Shipment",
  lastDelayCalculationTime: null,
  delayReasonUpdateDueTime: null,
  locationTrackingStatus: "UP TO DATE",
  poLineItemId: null,
  consignments: [
    {
      salesOrderId: null,
      fuLineItemIds: null,
      pod: null,
      customFields: [
        {
          indexedValue: ["Generated By_145.41"],
          fieldKey: "Generated By",
          multiple: false,
          description: null,
          remark: null,
          uuid: null,
          required: false,
          accessType: null,
          input: "string",
          unit: null,
          valueType: "string",
          options: null,
          fieldType: "text",
          value: "145.41",
          isRemark: false,
        },
        {
          indexedValue: ["Approved By_Dheeraj Kumar"],
          fieldKey: "Approved By",
          multiple: false,
          description: null,
          remark: null,
          uuid: null,
          required: false,
          accessType: null,
          input: "string",
          unit: null,
          valueType: "string",
          options: null,
          fieldType: "text",
          value: "Dheeraj Kumar",
          isRemark: false,
        },
      ],
      loadInfo: {
        material: "",
        valueOfGoods: 0,
        standardMeasurement: {
          volume: null,
          packageMeasurement: null,
          weight: null,
          containers: null,
          trucks: null,
        },
        currency: null,
        measurements: [
          {
            actualDeliveredQuantity: null,
            density: null,
            netQuantity: 0,
            moisture: null,
            claimQuantity: null,
            unitOfMeasurment: "unit",
            standardQuantity: 0,
            actualLoadedQuantity: null,
            measurmentType: "package",
            grossQuantity: 0,
            shortage: null,
            temperature: null,
            plannedLoadQuantity: null,
            frieghtDeductableQuantity: null,
          },
        ],
      },
      customerPsnNo: null,
      invoiceValue: "0.0",
      updates: {
        traceID: null,
        resourceId: "f395106b-253b-4381-9517-490bda65e6d5",
        updatedBy: "SYSTEM",
        changes: null,
        sourceOfInformation: null,
        description: null,
        forwardReasons: ["consignment.tracking.status.updated.event"],
        userId: null,
        uuid: "ccb4f8bd-6a2c-471d-a456-83c16ce99a18",
        revision: 5,
        time: 1687846873935,
        forwardedFrom: null,
        resourceType: "Consignment",
        updateType: null,
      },
      uuid: "f395106b-253b-4381-9517-490bda65e6d5",
      orgId: "495b8728-c761-4fa7-83fe-db75a7d63221",
      consigner: {
        geoFence: null,
        documents: null,
        customFields: null,
        isPortalEnabled: false,
        type: null,
        updates: null,
        uuid: "FAKE",
        orgId: "495b8728-c761-4fa7-83fe-db75a7d63221",
        firmType: null,
        gstn: null,
        voterId: null,
        verificationTicketId: null,
        group: {
          name: "Consignor",
          partnerType: null,
          uuid: null,
          orgId: null,
        },
        address: null,
        verificationStatus: null,
        externalId: null,
        panNumber: null,
        aadharNo: null,
        parentId: null,
        places: [
          {
            hubId: null,
            boundary: null,
            address:
              ",Noida,Dadri,Gautam Buddha Nagar,Uttar Pradesh,201301,India,in",
            accessibility: "public",
            addedBy: "495b8728-c761-4fa7-83fe-db75a7d63221",
            center: {
              latitude: 28.5707841,
              longitude: 77.3271074,
            },
            suggestedRadius: 500,
            isOwned: false,
            centerCoordinates: [77.3271074, 28.5707841],
            placeId: "4379cd6a-3683-42d4-873b-1af14713d9d3",
            geoJsonBoundry: null,
            externalId: null,
            source: "FRETRON",
            places: null,
            viewport: null,
            district: null,
            name: "Noida DC",
            state: null,
            category: "Unloading Point",
            subDistrict: null,
            controllingBranchId: null,
          },
        ],
        route: null,
        name: "Noida DC",
        location: null,
        fretronId: null,
        contacts: null,
        status: null,
      },
      lineItems: [
        {
          itemNumber: null,
          transportationServiceId: null,
          material: null,
          valueOfGoods: null,
          customFields: null,
          externalId: null,
          invoiceNo: null,
          customerMaterial: null,
          uuid: "727ca293-1813-43d3-af2d-0a4cff09ac91",
        },
      ],
      pssNo: null,
      eWayBillNumber: null,
      billingType: null,
      podDocument: null,
      invoiceNo: null,
      deliveryDate: null,
      associatedShipments: ["7606c6a5-25c7-4b98-84b4-4e8cfd27ba86"],
      originalEdd: null,
      consignee: {
        geoFence: null,
        documents: null,
        customFields: null,
        isPortalEnabled: false,
        type: null,
        updates: null,
        uuid: "FAKE",
        orgId: "495b8728-c761-4fa7-83fe-db75a7d63221",
        firmType: null,
        gstn: null,
        voterId: null,
        verificationTicketId: null,
        group: {
          name: "Consignee",
          partnerType: null,
          uuid: null,
          orgId: null,
        },
        address: null,
        verificationStatus: null,
        externalId: null,
        panNumber: null,
        aadharNo: null,
        parentId: null,
        places: [
          {
            hubId: null,
            boundary: null,
            address:
              ",Sector 108 Noida Central Park,Dadri,Gautam Buddha Nagar,Uttar Pradesh,201304,India,in",
            accessibility: "public",
            addedBy: "495b8728-c761-4fa7-83fe-db75a7d63221",
            center: {
              latitude: 28.5282895,
              longitude: 77.37752205000001,
            },
            suggestedRadius: 500,
            isOwned: false,
            centerCoordinates: [77.37752205000001, 28.5282895],
            placeId: "da24b682-f13f-456b-870e-27a5b1ca5a92",
            geoJsonBoundry: null,
            externalId: null,
            source: "FRETRON",
            places: null,
            viewport: null,
            district: null,
            name: "Noida Sec 80",
            state: null,
            category: "Unloading Point",
            subDistrict: null,
            controllingBranchId: null,
          },
        ],
        route: null,
        name: "Noida Sec 80",
        location: null,
        fretronId: null,
        contacts: [
          {
            emails: [""],
            address: null,
            mobileNumbers: ["9805131417"],
            mobileNumber: null,
            name: "karan mishra ",
            type: null,
          },
        ],
        status: null,
      },
      address: null,
      edd: null,
      salesOffice: null,
      consignmentDate: 1687845758000,
      externalId: "81729873",
      eWayBillExpiryDate: null,
      activeShipment: "7606c6a5-25c7-4b98-84b4-4e8cfd27ba86",
      consignmentNo: "81729873",
      currentLocation: null,
      billToParty: null,
      equipments: null,
      orderMappings: [
        {
          quantity: {
            volume: null,
            packageMeasurement: null,
            weight: null,
            containers: null,
            trucks: null,
          },
          orderId: null,
          lineItemId: null,
          legType: null,
          consignmentId: null,
          originLegId: null,
          isFullyUtilized: null,
          consignmentLineItemId: "727ca293-1813-43d3-af2d-0a4cff09ac91",
          source: null,
          containerId: null,
          uuid: null,
          fuMappings: null,
        },
      ],
      contractId: null,
      workOrderNumber: null,
      trackingStatus: "In Transit to Noida Sec 80",
      eWayBillRegistrationDate: null,
      contractToParty: null,
      invoiceStatus: null,
      poNumber: null,
      status: "In Transit",
    },
  ],
  customContacts: null,
  shipmentStages: [
    {
      departureTime: 1687846873204,
      gateInTime: 1687846870848,
      actualActivityStartTime: 1687846873204,
      actualActivityEndTime: 1687846873204,
      uuid: "07bb3c07-5d23-4c5e-a864-a0ba1855edb6",
      consignmentDelivered: null,
      resourceDropOff: null,
      resourcePickup: null,
      eta: null,
      stageName: null,
      hub: null,
      arrivalTime: 1687846868531,
      expectedActivityStartTime: null,
      secondaryStatus: null,
      consignmentPickUps: ["f395106b-253b-4381-9517-490bda65e6d5"],
      tripPoint: {
        outOfTrackSince: null,
        creationTime: null,
        purpose: "Pickup",
        plannedArrival: null,
        currentGpsState: null,
        updates: null,
        uuid: "07bb3c07-5d23-4c5e-a864-a0ba1855edb6",
        sequenceId: null,
        isDisconnected: false,
        isOutOfTrack: false,
        routeDeviationMinimumDistanceConstraint: null,
        eta: null,
        routeId: null,
        expectedActivityStartTime: null,
        actualDeparture: 1687846873204,
        vehicleId: null,
        place: {
          hubId: null,
          boundary: null,
          address:
            ",Noida,Dadri,Gautam Buddha Nagar,Uttar Pradesh,201301,India,in",
          accessibility: "public",
          addedBy: "495b8728-c761-4fa7-83fe-db75a7d63221",
          center: {
            latitude: 28.5707841,
            longitude: 77.3271074,
          },
          suggestedRadius: 500,
          isOwned: false,
          centerCoordinates: [77.3271074, 28.5707841],
          placeId: "4379cd6a-3683-42d4-873b-1af14713d9d3",
          geoJsonBoundry: null,
          externalId: null,
          source: "FRETRON",
          places: null,
          viewport: null,
          district: null,
          name: "Noida DC",
          state: null,
          category: "Unloading Point",
          subDistrict: null,
          controllingBranchId: null,
        },
        remainingDistance: null,
        actualActivityStartTime: null,
        forShipmentStages: ["07bb3c07-5d23-4c5e-a864-a0ba1855edb6"],
        actualActivityEndTime: null,
        actualArrival: 1687846868531,
        purposedDistance: null,
        plannedDeparture: null,
        currentLocation: null,
        isAutoCompleted: false,
        coveredDistance: null,
        hub: null,
        imei: null,
        assosiatedShipmentsId: ["7606c6a5-25c7-4b98-84b4-4e8cfd27ba86"],
        status: "COMPLETED",
      },
      place: {
        hubId: null,
        boundary: null,
        address:
          ",Noida,Dadri,Gautam Buddha Nagar,Uttar Pradesh,201301,India,in",
        accessibility: "public",
        addedBy: "495b8728-c761-4fa7-83fe-db75a7d63221",
        center: {
          latitude: 28.5707841,
          longitude: 77.3271074,
        },
        suggestedRadius: 500,
        isOwned: false,
        centerCoordinates: [77.3271074, 28.5707841],
        placeId: "4379cd6a-3683-42d4-873b-1af14713d9d3",
        geoJsonBoundry: null,
        externalId: null,
        source: "FRETRON",
        places: null,
        viewport: null,
        district: null,
        name: "Noida DC",
        state: null,
        category: "Unloading Point",
        subDistrict: null,
        controllingBranchId: null,
      },
      controllingBranchId: null,
      gateOutTime: null,
      status: "COMPLETED",
    },
    {
      departureTime: null,
      gateInTime: null,
      actualActivityStartTime: null,
      actualActivityEndTime: null,
      uuid: "13900911-15bc-4279-9051-dc8fd92ebd30",
      consignmentDelivered: ["f395106b-253b-4381-9517-490bda65e6d5"],
      resourceDropOff: null,
      resourcePickup: null,
      eta: null,
      stageName: null,
      hub: null,
      arrivalTime: null,
      expectedActivityStartTime: null,
      secondaryStatus: null,
      consignmentPickUps: null,
      tripPoint: {
        outOfTrackSince: null,
        creationTime: null,
        purpose: "Delivery",
        plannedArrival: null,
        currentGpsState: null,
        updates: null,
        uuid: null,
        sequenceId: null,
        isDisconnected: false,
        isOutOfTrack: false,
        routeDeviationMinimumDistanceConstraint: null,
        eta: null,
        routeId: null,
        expectedActivityStartTime: null,
        actualDeparture: null,
        vehicleId: null,
        place: null,
        remainingDistance: null,
        actualActivityStartTime: null,
        forShipmentStages: null,
        actualActivityEndTime: null,
        actualArrival: null,
        purposedDistance: null,
        plannedDeparture: null,
        currentLocation: null,
        isAutoCompleted: false,
        coveredDistance: null,
        hub: null,
        imei: null,
        assosiatedShipmentsId: null,
        status: "UPCOMING",
      },
      place: {
        hubId: null,
        boundary: null,
        address:
          ",Sector 108 Noida Central Park,Dadri,Gautam Buddha Nagar,Uttar Pradesh,201304,India,in",
        accessibility: "public",
        addedBy: "495b8728-c761-4fa7-83fe-db75a7d63221",
        center: {
          latitude: 28.5282895,
          longitude: 77.37752205000001,
        },
        suggestedRadius: 500,
        isOwned: false,
        centerCoordinates: [77.37752205000001, 28.5282895],
        placeId: "da24b682-f13f-456b-870e-27a5b1ca5a92",
        geoJsonBoundry: null,
        externalId: null,
        source: "FRETRON",
        places: null,
        viewport: null,
        district: null,
        name: "Noida Sec 80",
        state: null,
        category: "Unloading Point",
        subDistrict: null,
        controllingBranchId: null,
      },
      controllingBranchId: null,
      gateOutTime: null,
      status: "UPCOMING",
    },
    {
      departureTime: null,
      gateInTime: null,
      actualActivityStartTime: null,
      actualActivityEndTime: null,
      uuid: "44411b1a-16f2-41e8-8d26-39429956ff04",
      consignmentDelivered: null,
      resourceDropOff: null,
      resourcePickup: null,
      eta: null,
      stageName: null,
      hub: null,
      arrivalTime: null,
      expectedActivityStartTime: null,
      secondaryStatus: null,
      consignmentPickUps: null,
      tripPoint: {
        outOfTrackSince: null,
        creationTime: null,
        purpose: "Delivery",
        plannedArrival: null,
        currentGpsState: null,
        updates: null,
        uuid: null,
        sequenceId: null,
        isDisconnected: false,
        isOutOfTrack: false,
        routeDeviationMinimumDistanceConstraint: null,
        eta: null,
        routeId: null,
        expectedActivityStartTime: null,
        actualDeparture: null,
        vehicleId: null,
        place: null,
        remainingDistance: null,
        actualActivityStartTime: null,
        forShipmentStages: null,
        actualActivityEndTime: null,
        actualArrival: null,
        purposedDistance: null,
        plannedDeparture: null,
        currentLocation: null,
        isAutoCompleted: false,
        coveredDistance: null,
        hub: null,
        imei: null,
        assosiatedShipmentsId: null,
        status: "NEXT",
      },
      place: {
        hubId: null,
        boundary: null,
        address:
          ",Noida,Dadri,Gautam Buddha Nagar,Uttar Pradesh,201301,India,in",
        accessibility: "public",
        addedBy: "495b8728-c761-4fa7-83fe-db75a7d63221",
        center: {
          latitude: 28.5707841,
          longitude: 77.3271074,
        },
        suggestedRadius: 500,
        isOwned: false,
        centerCoordinates: [77.3271074, 28.5707841],
        placeId: "4379cd6a-3683-42d4-873b-1af14713d9d3",
        geoJsonBoundry: null,
        externalId: null,
        source: "FRETRON",
        places: null,
        viewport: null,
        district: null,
        name: "Noida DC",
        state: null,
        category: "Unloading Point",
        subDistrict: null,
        controllingBranchId: null,
      },
      controllingBranchId: null,
      gateOutTime: null,
      status: "NEXT",
    },
  ],
  remarks: null,
  syncUpExpiryTime: null,
  shipmentStatus: "Created",
};

async function epodLinkTrigger(payload) {
  let url = `http://apis.fretron.com/sharing-utils/v1/share-cn`;
  try {
    let res = await rp({
      method: "POST",
      uri: url,
      body: payload,
      json: true,
      headers: {
        Authorization: TOKEN,
      },
    });
    console.log(`EpodLink :${res}`);
    if (res.status === 200) {
      return res.data;
    } else {
      console.log(`ePOD Link not triggered, error: ${res.error}`);
    }
  } catch (e) {
    console.log(`ePOD Link not triggered, caught error: ${e.message}`);
  }
  return null;
}

async function sendSms(mobileNumber, content) {
  let url = `http://apis.fretron.com/notifications/smsing/sms`;
  try {
    let res = await rp({
      method: "POST",
      uri: url,
      body: {
        to: mobileNumber,
        content: content,
      },
      json: true,
    });
    if (res.status === 200) {
      return res.data;
    } else {
      console.log(`SMS not sent, error: ${res.error}`);
    }
  } catch (e) {
    console.log(`SMS not sent, caught error: ${e.message}`);
  }
  return null;
}

async function main() {
  try {
    const consignments = $event.consignments;
    const shipmentTrackingStatus = $event.shipmentTrackingStatus;
    if (consignments && consignments.length > 0) {
      if (shipmentTrackingStatus === "At Delivery Point") {
        const consignee = consignments[0]?.consignee;

        if (consignee && consignee.contacts && consignee.contacts.length > 0) {
          const mobileNumbers = [];

          for (const contact of consignee.contacts) {
            if (contact.mobileNumbers && contact.mobileNumbers.length > 0) {
              mobileNumbers.push(...contact.mobileNumbers);
            }
          }

          if (mobileNumbers.length > 0) {
            console.log("Mobile Numbers:", mobileNumbers);

            const payload = {
              consignmentId: consignments[0].uuid,
              uiRestrictions: {
                cnInfo: {
                  consignmentNo: true,
                  vehicleInfo: true,
                  materialInfo: true,
                  consignor: true,
                  consignee: true,
                  origin: true,
                  destination: true,
                  customer: false,
                  valuOfGoods: false,
                  currentStatus: true,
                  currentAddress: false,
                },
                epod: {
                  upload: true,
                  timing: true,
                  feeding: true,
                  otpToDriver: false,
                  unloadingStart: true,
                  unloadingEnd: true,
                  reportingTime: true,
                  vehicleReleaseTime: true,
                  unloadingCharge: false,
                  isMandateTiming: false,
                  isMandateFeeding: true,
                  markManually: true,
                  otpToConsignee: false,
                },
                map: false,
                liveTracking: false,
                updateTracking: false,
                miscFields: false,
                customFields: [],
              },
            };

            const ePodLink = await epodLinkTrigger(payload);
            if (ePodLink) {
              const cnNumber = consignments[0].consignmentNo;
              const url = `https://alpha.fretron.com/trip-share/vehicleLocation/consignment?code=${ePodLink}`;
              const content = `Jubilant Agri and Consumer shared consignment ${cnNumber} with you. Click the link below to track ${url}`;

              for (const mobileNumber of mobileNumbers) {
                await sendSms(mobileNumber, content);
              }
            } else {
              console.log("Failed to trigger ePOD link.");
            }
          } else {
            console.log(`No mobile numbers found for consignee.`);
          }
        } else {
          console.log(`No contacts found for consignee.`);
        }
      } else {
        console.log("Shipment tracking status is not 'At Delivery Point'.");
      }
    } else {
      console.log("No consignments found.");
    }
  } catch (error) {
    console.error("An error occurred in main function:", error.message);
  }
}
main();
